import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ApiClientError } from '@/api/api-client';
import { deleteClasses, exportClasses, getClassPage, type ClassFileFormat, type ClassRecord } from '@/api/classes';
import { FileFormatChooser } from '@/components/file-format-chooser';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { Spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
import { shareBinaryFile } from '@/utils/file-sharing';

const SIZE = 10;
export default function ClassesScreen() {
  const router = useRouter(); const client = useQueryClient(); const theme = useTheme(); const [page, setPage] = useState(1); const [input, setInput] = useState(''); const [search, setSearch] = useState(''); const [selecting, setSelecting] = useState(false); const [selected, setSelected] = useState<string[]>([]); const [format, setFormat] = useState<ClassFileFormat>('xlsx');
  const query = useQuery({ queryKey: ['classes', { page, size: SIZE, search }], queryFn: () => getClassPage({ page, size: SIZE, search }) }); const data = query.data?.data; const records = data?.records ?? []; const current = data?.page_info.current ?? page; const total = data?.page_info.total_pages ?? 0;
  const exportMutation = useMutation({ mutationFn: () => exportClasses(selected, format).then(shareBinaryFile) });
  const removeMutation = useMutation({ mutationFn: () => deleteClasses(selected), onSuccess: async (response) => { await client.invalidateQueries({ queryKey: ['classes'] }); const deleted = new Set(response.data.deletedIds.map(String)); setSelected((items) => items.filter((id) => !deleted.has(id))); Alert.alert('Kết quả xóa', `Đã xóa ${response.data.deletedIds.length} lớp.${response.data.blockedIds.length ? ` Không thể xóa ${response.data.blockedIds.length} lớp còn sinh viên: ${response.data.blockedIds.join(', ')}.` : ''}`); } });
  const toggle = (id: string) => setSelected((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]); const submit = () => { setSearch(input.trim()); setPage(1); }; const error = query.error instanceof ApiClientError ? `${query.error.code ? `${query.error.code}: ` : ''}${query.error.message}` : 'Không thể tải danh sách lớp.';
  const confirmDelete = () => Alert.alert('Xóa lớp đã chọn?', `${selected.length} lớp được gửi xóa. Những lớp còn sinh viên sẽ bị chặn; các lớp khác vẫn có thể bị xóa.`, [{ text: 'Hủy', style: 'cancel' }, { text: 'Xóa', style: 'destructive', onPress: () => removeMutation.mutate() }]);
  return <ThemedView style={s.container}><SafeAreaView style={s.container}><FlatList data={records} keyExtractor={(item) => item.id} renderItem={({ item }: { item: ClassRecord }) => <Pressable onPress={() => selecting ? toggle(item.id) : router.push({ pathname: '/classes/[id]', params: { id: item.id } } as never)}><ThemedView type="backgroundElement" style={s.card}><ThemedText type="smallBold">{selecting ? `${selected.includes(item.id) ? '✓ ' : '○ '}` : ''}{item.code} — {item.name}</ThemedText>{item.description ? <ThemedText type="small" themeColor="textSecondary">{item.description}</ThemedText> : null}<ThemedText type="small" themeColor="textSecondary">{Number(item.student_count)} sinh viên</ThemedText></ThemedView></Pressable>}
    ListHeaderComponent={<ThemedView style={s.header}><ThemedText type="subtitle">Lớp</ThemedText><ThemedText themeColor="textSecondary">Tìm theo mã, tên hoặc mô tả.</ThemedText><View style={s.actions}><Pressable onPress={() => router.push('/classes/new' as never)} style={s.primary}><ThemedText type="smallBold" style={s.white}>Thêm lớp</ThemedText></Pressable><Pressable onPress={() => router.push('/classes/import' as never)} style={s.secondary}><ThemedText type="smallBold">Nhập</ThemedText></Pressable><Pressable onPress={() => setSelecting((value) => !value)} style={s.secondary}><ThemedText type="smallBold">{selecting ? 'Xong chọn' : 'Chọn nhiều'}</ThemedText></Pressable></View>{selecting ? <ThemedView type="backgroundElement" style={s.selection}><ThemedText type="smallBold">Đã chọn {selected.length}</ThemedText><View style={s.actions}><Pressable onPress={() => setSelected((items) => [...new Set([...items, ...records.map((record) => record.id)])])} style={s.secondary}><ThemedText type="smallBold">Chọn trang này</ThemedText></Pressable><Pressable onPress={() => setSelected([])} style={s.secondary}><ThemedText type="smallBold">Bỏ chọn</ThemedText></Pressable>{selected.length ? <Pressable onPress={() => router.push({ pathname: '/classes/copy-preview', params: { ids: selected.join(',') } } as never)} style={s.primary}><ThemedText type="smallBold" style={s.white}>Sao chép</ThemedText></Pressable> : null}</View>{selected.length ? <><ThemedText type="small">Xuất định dạng</ThemedText><FileFormatChooser value={format} onChange={setFormat} /><Pressable disabled={exportMutation.isPending} onPress={() => exportMutation.mutate()} style={[s.primary, exportMutation.isPending && s.disabled]}><ThemedText type="smallBold" style={s.white}>{exportMutation.isPending ? 'Đang chuẩn bị...' : 'Xuất'}</ThemedText></Pressable><Pressable disabled={removeMutation.isPending} onPress={confirmDelete} style={[s.delete, removeMutation.isPending && s.disabled]}><ThemedText type="smallBold" style={s.white}>{removeMutation.isPending ? 'Đang xóa...' : 'Xóa'}</ThemedText></Pressable></> : null}{exportMutation.isError ? <ThemedText type="small" style={s.error}>{exportMutation.error instanceof ApiClientError ? exportMutation.error.message : 'Không thể xuất tệp.'}</ThemedText> : null}{removeMutation.isError ? <ThemedText type="small" style={s.error}>{removeMutation.error instanceof ApiClientError ? removeMutation.error.message : 'Không thể xóa lớp.'}</ThemedText> : null}</ThemedView> : null}<View style={s.searchRow}><TextInput value={input} onChangeText={setInput} onSubmitEditing={submit} returnKeyType="search" placeholder="Nhập mã, tên hoặc mô tả" placeholderTextColor={theme.textSecondary} style={[s.input, { borderColor: theme.backgroundSelected, color: theme.text }]} /><Pressable onPress={submit} style={s.search}><ThemedText type="smallBold" style={s.white}>Tìm</ThemedText></Pressable></View></ThemedView>}
    ListEmptyComponent={query.isPending ? <ActivityIndicator size="large" color={theme.text} /> : <ThemedView type="backgroundElement" style={s.state}><ThemedText type="smallBold">{query.isError ? 'Đã xảy ra lỗi' : 'Không có lớp phù hợp.'}</ThemedText>{query.isError ? <><ThemedText type="small">{error}</ThemedText><Pressable onPress={() => void query.refetch()}><ThemedText type="smallBold">Thử lại</ThemedText></Pressable></> : null}</ThemedView>}
    ListFooterComponent={data ? <ThemedView style={s.pagination}><Pressable disabled={current <= 1} onPress={() => setPage((value) => Math.max(1, value - 1))} style={[s.page, current <= 1 && s.disabled]}><ThemedText type="smallBold">Trước</ThemedText></Pressable><ThemedText type="small">Trang {current}/{total || 1} · {data.page_info.total_items} lớp</ThemedText><Pressable disabled={!total || current >= total} onPress={() => setPage((value) => value + 1)} style={[s.page, (!total || current >= total) && s.disabled]}><ThemedText type="smallBold">Sau</ThemedText></Pressable></ThemedView> : null} contentContainerStyle={[s.content, !records.length && s.empty]} refreshing={query.isRefetching} onRefresh={() => void query.refetch()} /></SafeAreaView></ThemedView>;
}
const s = StyleSheet.create({ container: { flex: 1 }, content: { gap: Spacing.two, padding: Spacing.four }, empty: { flexGrow: 1 }, header: { gap: Spacing.two, paddingBottom: Spacing.three }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.two }, primary: { alignSelf: 'flex-start', backgroundColor: '#0A7EA4', borderRadius: Spacing.two, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two }, secondary: { alignSelf: 'flex-start', borderColor: '#0A7EA4', borderRadius: Spacing.two, borderWidth: 1, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two }, delete: { alignSelf: 'flex-start', backgroundColor: '#B42318', borderRadius: Spacing.two, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two }, white: { color: '#FFF' }, searchRow: { flexDirection: 'row', gap: Spacing.two }, input: { borderWidth: 1, borderRadius: Spacing.two, flex: 1, fontSize: 16, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two }, search: { alignItems: 'center', backgroundColor: '#0A7EA4', borderRadius: Spacing.two, justifyContent: 'center', paddingHorizontal: Spacing.three }, card: { gap: Spacing.one, padding: Spacing.three, borderRadius: Spacing.two }, state: { alignItems: 'center', gap: Spacing.two, marginTop: Spacing.four, padding: Spacing.four, borderRadius: Spacing.two }, pagination: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingTop: Spacing.three }, page: { padding: Spacing.two }, selection: { gap: Spacing.two, padding: Spacing.three, borderRadius: Spacing.two }, disabled: { opacity: .4 }, error: { color: '#B42318' } });
