import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'expo-router';
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, TextInput, View, type ListRenderItemInfo } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ApiClientError } from '@/api/api-client';
import { deleteStudents, exportStudents, getStudentPage, type StudentFileFormat, type StudentListItem } from '@/api/students';
import { FileFormatChooser } from '@/components/file-format-chooser';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { Spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
import { shareBinaryFile } from '@/utils/file-sharing';

const PAGE_SIZE = 10;

function StudentCard({ student, selecting, selected, onPress, onToggle }: { student: StudentListItem; selecting: boolean; selected: boolean; onPress: () => void; onToggle: () => void }) {
  return <Pressable onPress={selecting ? onToggle : onPress}><ThemedView type="backgroundElement" style={styles.studentCard}><ThemedText type="smallBold">{selecting ? `${selected ? '✓ ' : '○ '}` : ''}{student.fullname}</ThemedText><ThemedText type="small" themeColor="textSecondary">Mã sinh viên: {student.code}</ThemedText><ThemedText type="small" themeColor="textSecondary">{student.email}</ThemedText></ThemedView></Pressable>;
}

export default function StudentsScreen() {
  const router = useRouter(); const queryClient = useQueryClient(); const theme = useTheme();
  const [page, setPage] = useState(1); const [searchInput, setSearchInput] = useState(''); const [search, setSearch] = useState('');
  const [selectionMode, setSelectionMode] = useState(false); const [selectedIds, setSelectedIds] = useState<string[]>([]); const [exportFormat, setExportFormat] = useState<StudentFileFormat>('xlsx');
  const studentsQuery = useQuery({ queryKey: ['students', { page, size: PAGE_SIZE, search }], queryFn: () => getStudentPage({ page, size: PAGE_SIZE, search }) });
  const pageData = studentsQuery.data?.data; const students = pageData?.records ?? []; const currentPage = pageData?.page_info.current ?? page; const totalPages = pageData?.page_info.total_pages ?? 0;
  const exportMutation = useMutation({ mutationFn: () => exportStudents(selectedIds, exportFormat).then(shareBinaryFile) });
  const deleteMutation = useMutation({
    mutationFn: () => deleteStudents(selectedIds),
    onSuccess: async (response) => {
      const deleted = new Set(response.data.deleted.map(String));
      await queryClient.invalidateQueries({ queryKey: ['students'] });
      await queryClient.invalidateQueries({ queryKey: ['deleted-students'] });
      response.data.deleted.forEach((id) => queryClient.removeQueries({ queryKey: ['student', String(id)] }));
      setSelectedIds((current) => current.filter((id) => !deleted.has(id)));
      if (students.length > 0 && students.every((student) => deleted.has(student.id))) setPage((current) => Math.max(1, current - 1));
      Alert.alert('Kết quả xóa', `Đã chuyển ${response.data.deleted.length} sinh viên vào danh sách đã xóa.${response.data.notFound.length ? ` Không tìm thấy: ${response.data.notFound.join(', ')}.` : ''}`);
    },
  });
  const submitSearch = () => { setSearch(searchInput.trim()); setPage(1); };
  const toggle = (id: string) => setSelectedIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const renderItem = ({ item }: ListRenderItemInfo<StudentListItem>) => <StudentCard student={item} selecting={selectionMode} selected={selectedIds.includes(item.id)} onToggle={() => toggle(item.id)} onPress={() => router.push({ pathname: '/students/[id]', params: { id: item.id } })} />;
  const error = studentsQuery.error instanceof ApiClientError ? `${studentsQuery.error.code ? `${studentsQuery.error.code}: ` : ''}${studentsQuery.error.message}` : 'Không thể tải danh sách sinh viên.';
  return <ThemedView style={styles.container}><SafeAreaView style={styles.safeArea}><FlatList data={students} keyExtractor={(student) => student.id} renderItem={renderItem}
    ListHeaderComponent={<ThemedView style={styles.header}><ThemedText type="subtitle">Sinh viên</ThemedText><ThemedText themeColor="textSecondary">Tìm theo tên hoặc email.</ThemedText><View style={styles.actions}><Pressable onPress={() => router.push('/students/new')} style={styles.primaryAction}><ThemedText type="smallBold" style={styles.primaryText}>Thêm sinh viên</ThemedText></Pressable><Pressable onPress={() => router.push('/students/deleted')} style={styles.secondaryAction}><ThemedText type="smallBold">Đã xóa</ThemedText></Pressable><Pressable onPress={() => router.push('/students/import')} style={styles.secondaryAction}><ThemedText type="smallBold">Nhập</ThemedText></Pressable><Pressable onPress={() => setSelectionMode((value) => !value)} style={styles.secondaryAction}><ThemedText type="smallBold">{selectionMode ? 'Xong chọn' : 'Chọn nhiều'}</ThemedText></Pressable></View>
      {selectionMode ? <ThemedView type="backgroundElement" style={styles.selectionBar}><ThemedText type="smallBold">Đã chọn {selectedIds.length}</ThemedText><View style={styles.actions}><Pressable onPress={() => setSelectedIds((current) => [...new Set([...current, ...students.map((student) => student.id)])])} style={styles.secondaryAction}><ThemedText type="smallBold">Chọn trang này</ThemedText></Pressable><Pressable onPress={() => setSelectedIds([])} style={styles.secondaryAction}><ThemedText type="smallBold">Bỏ chọn</ThemedText></Pressable>{selectedIds.length ? <Pressable onPress={() => router.push({ pathname: '/students/copy-preview', params: { ids: selectedIds.join(',') } })} style={styles.primaryAction}><ThemedText type="smallBold" style={styles.primaryText}>Sao chép</ThemedText></Pressable> : null}</View>{selectedIds.length ? <><ThemedText type="small">Xuất định dạng</ThemedText><FileFormatChooser value={exportFormat} onChange={setExportFormat} /><Pressable disabled={exportMutation.isPending} onPress={() => exportMutation.mutate()} style={[styles.primaryAction, exportMutation.isPending && styles.disabled]}><ThemedText type="smallBold" style={styles.primaryText}>{exportMutation.isPending ? 'Đang chuẩn bị...' : 'Xuất'}</ThemedText></Pressable><Pressable disabled={deleteMutation.isPending} onPress={() => Alert.alert('Xóa sinh viên đã chọn?', `${selectedIds.length} sinh viên sẽ được chuyển vào danh sách đã xóa.`, [{ text: 'Hủy', style: 'cancel' }, { text: 'Xóa', style: 'destructive', onPress: () => deleteMutation.mutate() }])} style={[styles.deleteAction, deleteMutation.isPending && styles.disabled]}><ThemedText type="smallBold" style={styles.primaryText}>{deleteMutation.isPending ? 'Đang xóa...' : 'Xóa'}</ThemedText></Pressable></> : null}{exportMutation.isError ? <ThemedText type="small" style={styles.error}>{exportMutation.error instanceof ApiClientError ? `${exportMutation.error.code ? `${exportMutation.error.code}: ` : ''}${exportMutation.error.message}` : 'Không thể xuất tệp.'}</ThemedText> : null}{deleteMutation.isError ? <ThemedText type="small" style={styles.error}>{deleteMutation.error instanceof ApiClientError ? `${deleteMutation.error.code ? `${deleteMutation.error.code}: ` : ''}${deleteMutation.error.message}` : 'Không thể xóa sinh viên.'}</ThemedText> : null}</ThemedView> : null}
      <View style={styles.searchRow}><TextInput value={searchInput} onChangeText={setSearchInput} onSubmitEditing={submitSearch} placeholder="Nhập tên hoặc email" placeholderTextColor={theme.textSecondary} returnKeyType="search" style={[styles.searchInput, { borderColor: theme.backgroundSelected, color: theme.text }]} /><Pressable onPress={submitSearch} style={styles.searchButton}><ThemedText type="smallBold" style={styles.primaryText}>Tìm</ThemedText></Pressable></View></ThemedView>}
    ListEmptyComponent={studentsQuery.isPending ? <ActivityIndicator color={theme.text} size="large" /> : studentsQuery.isError ? <ThemedView type="backgroundElement" style={styles.stateCard}><ThemedText type="smallBold">Đã xảy ra lỗi</ThemedText><ThemedText type="small">{error}</ThemedText><Pressable onPress={() => void studentsQuery.refetch()}><ThemedText type="smallBold">Thử lại</ThemedText></Pressable></ThemedView> : <ThemedView type="backgroundElement" style={styles.stateCard}><ThemedText type="small">Không có sinh viên phù hợp.</ThemedText></ThemedView>}
    ListFooterComponent={pageData ? <View style={styles.pagination}><Pressable disabled={currentPage <= 1} onPress={() => setPage((current) => Math.max(1, current - 1))}><ThemedText type="smallBold">Trước</ThemedText></Pressable><ThemedText type="small">Trang {currentPage}/{totalPages || 1} · {pageData.page_info.total_items}</ThemedText><Pressable disabled={!(totalPages > 0 && currentPage < totalPages)} onPress={() => setPage((current) => current + 1)}><ThemedText type="smallBold">Sau</ThemedText></Pressable></View> : null}
    contentContainerStyle={[styles.listContent, students.length === 0 && styles.emptyContent]} refreshing={studentsQuery.isRefetching} onRefresh={() => void studentsQuery.refetch()} /></SafeAreaView></ThemedView>;
}

const styles = StyleSheet.create({ container: { flex: 1 }, safeArea: { flex: 1 }, listContent: { padding: Spacing.four, gap: Spacing.two }, emptyContent: { flexGrow: 1 }, header: { gap: Spacing.two, paddingBottom: Spacing.three }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.two }, primaryAction: { backgroundColor: '#0A7EA4', borderRadius: Spacing.two, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two }, primaryText: { color: '#FFFFFF' }, secondaryAction: { borderColor: '#0A7EA4', borderRadius: Spacing.two, borderWidth: 1, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two }, deleteAction: { backgroundColor: '#B42318', borderRadius: Spacing.two, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two }, searchRow: { flexDirection: 'row', gap: Spacing.two }, searchInput: { borderWidth: 1, borderRadius: Spacing.two, flex: 1, fontSize: 16, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two }, searchButton: { alignItems: 'center', backgroundColor: '#0A7EA4', borderRadius: Spacing.two, justifyContent: 'center', paddingHorizontal: Spacing.three }, studentCard: { gap: Spacing.half, padding: Spacing.three, borderRadius: Spacing.two }, stateCard: { alignItems: 'center', gap: Spacing.two, marginTop: Spacing.four, padding: Spacing.four, borderRadius: Spacing.two }, pagination: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingTop: Spacing.three }, selectionBar: { gap: Spacing.two, padding: Spacing.three, borderRadius: Spacing.two }, disabled: { opacity: 0.45 }, error: { color: '#B42318' } });
