import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { ApiClientError } from '@/api/api-client';
import { copyClass, deleteClass, getClass } from '@/api/classes';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { Spacing } from '@/constants/theme';

export default function ClassDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const client = useQueryClient(); const query = useQuery({ queryKey: ['class', id], queryFn: () => getClass(id), enabled: Boolean(id) }); const record = query.data?.data;
  const copy = useMutation({ mutationFn: () => copyClass(id), onSuccess: async (response) => { await client.invalidateQueries({ queryKey: ['classes'] }); router.replace({ pathname: '/classes/[id]', params: { id: response.data.id } } as never); } });
  const remove = useMutation({ mutationFn: () => deleteClass(id), onSuccess: async () => { await client.invalidateQueries({ queryKey: ['classes'] }); client.removeQueries({ queryKey: ['class', id] }); router.replace('/classes'); } });
  const error = (value: unknown, fallback: string) => value instanceof ApiClientError ? `${value.code ? `${value.code}: ` : ''}${value.message}` : fallback;
  if (query.isPending) return <ThemedView style={s.center}><ActivityIndicator /></ThemedView>;
  if (!record) return <ThemedView style={s.center}><ThemedText type="smallBold">Không tìm thấy lớp</ThemedText><ThemedText type="small" themeColor="textSecondary">{query.isError ? error(query.error, 'Không thể tải lớp.') : 'Lớp không còn tồn tại.'}</ThemedText><Pressable onPress={() => void query.refetch()}><ThemedText type="smallBold">Thử lại</ThemedText></Pressable></ThemedView>;
  const blocked = Number(record.student_count) > 0;
  return <ThemedView style={s.container}><ScrollView contentContainerStyle={s.content}><ThemedView type="backgroundElement" style={s.card}><ThemedText type="subtitle">{record.name}</ThemedText><ThemedText type="small" themeColor="textSecondary">Mã lớp: {record.code}</ThemedText><ThemedText type="small" themeColor="textSecondary">{Number(record.student_count)} sinh viên</ThemedText></ThemedView><ThemedView type="backgroundElement" style={s.card}><ThemedText type="smallBold">Mô tả</ThemedText><ThemedText type="small" themeColor="textSecondary">{record.description || '—'}</ThemedText></ThemedView><Pressable onPress={() => router.push({ pathname: '/classes/[id]/membership', params: { id } } as never)} style={s.membership}><ThemedText type="smallBold">Sinh viên thuộc lớp</ThemedText><ThemedText type="small" themeColor="textSecondary">Xem, thêm hoặc loại sinh viên</ThemedText></Pressable>{copy.isError ? <ThemedText type="small" style={s.error}>{error(copy.error, 'Không thể sao chép lớp.')}</ThemedText> : null}{remove.isError ? <ThemedText type="small" style={s.error}>{error(remove.error, 'Không thể xóa lớp.')}</ThemedText> : null}<View style={s.actions}><Pressable onPress={() => router.push({ pathname: '/classes/[id]/edit', params: { id } } as never)} style={s.primary}><ThemedText type="smallBold" style={s.white}>Sửa</ThemedText></Pressable><Pressable disabled={copy.isPending} onPress={() => copy.mutate()} style={s.secondary}><ThemedText type="smallBold">{copy.isPending ? 'Đang sao chép...' : 'Sao chép'}</ThemedText></Pressable><Pressable disabled={blocked || remove.isPending} onPress={() => Alert.alert('Xóa lớp?', 'Lớp không có sinh viên sẽ bị xóa.', [{ text: 'Hủy', style: 'cancel' }, { text: 'Xóa', style: 'destructive', onPress: () => remove.mutate() }])} style={[s.delete, (blocked || remove.isPending) && s.disabled]}><ThemedText type="smallBold" style={s.white}>{blocked ? 'Còn sinh viên' : remove.isPending ? 'Đang xóa...' : 'Xóa'}</ThemedText></Pressable></View></ScrollView></ThemedView>;
}
const s = StyleSheet.create({ container: { flex: 1 }, content: { gap: Spacing.three, padding: Spacing.four }, card: { gap: Spacing.one, padding: Spacing.three, borderRadius: Spacing.two }, membership: { gap: Spacing.one, borderColor: '#0A7EA4', borderRadius: Spacing.two, borderWidth: 1, padding: Spacing.three }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.two }, primary: { backgroundColor: '#0A7EA4', borderRadius: Spacing.two, padding: Spacing.three }, secondary: { borderColor: '#0A7EA4', borderRadius: Spacing.two, borderWidth: 1, padding: Spacing.three }, delete: { backgroundColor: '#B42318', borderRadius: Spacing.two, padding: Spacing.three }, white: { color: '#FFF' }, disabled: { opacity: .45 }, error: { color: '#B42318' }, center: { alignItems: 'center', flex: 1, gap: Spacing.two, justifyContent: 'center', padding: Spacing.four } });
