import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, TextInput } from 'react-native';
import { ApiClientError } from '@/api/api-client';
import { getClassStudents, removeClassStudent, type ClassStudent } from '@/api/classes';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { Spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';
const SIZE = 10;
export default function MembershipScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const theme = useTheme(); const client = useQueryClient(); const [page, setPage] = useState(1); const [input, setInput] = useState(''); const [search, setSearch] = useState('');
  const query = useQuery({ queryKey: ['class-members', id, { page, size: SIZE, search }], queryFn: () => getClassStudents(id, { page, size: SIZE, search }), enabled: Boolean(id) }); const data = query.data?.data; const records = data?.records ?? []; const current = data?.page_info.current ?? page; const total = data?.page_info.total_pages ?? 0;
  const remove = useMutation({ mutationFn: (studentId: string) => removeClassStudent(id, studentId), onSuccess: async () => { await client.invalidateQueries({ queryKey: ['class', id] }); await client.invalidateQueries({ queryKey: ['class-members', id] }); await client.invalidateQueries({ queryKey: ['class-available', id] }); await client.invalidateQueries({ queryKey: ['students'] }); await client.invalidateQueries({ queryKey: ['student'] }); } }); const error = (e: unknown) => e instanceof ApiClientError ? `${e.code ? `${e.code}: ` : ''}${e.message}` : 'Không thể tải sinh viên.';
  return <ThemedView style={s.container}><FlatList data={records} keyExtractor={(item) => item.id} renderItem={({ item }: { item: ClassStudent }) => <ThemedView type="backgroundElement" style={s.card}><ThemedText type="smallBold">{item.fullname}</ThemedText><ThemedText type="small" themeColor="textSecondary">{item.code} · {item.email}</ThemedText><Pressable disabled={remove.isPending} onPress={() => Alert.alert('Loại sinh viên?', `${item.fullname} sẽ không còn thuộc lớp này.`, [{ text: 'Hủy', style: 'cancel' }, { text: 'Loại', style: 'destructive', onPress: () => remove.mutate(item.id) }])}><ThemedText type="smallBold" style={s.danger}>Loại khỏi lớp</ThemedText></Pressable></ThemedView>}
    ListHeaderComponent={<ThemedView style={s.header}><Pressable onPress={() => router.push({ pathname: '/classes/[id]/membership/add', params: { id } } as never)} style={s.primary}><ThemedText type="smallBold" style={s.white}>Thêm sinh viên vào lớp</ThemedText></Pressable><ThemedView style={s.row}><TextInput value={input} onChangeText={setInput} onSubmitEditing={() => { setSearch(input.trim()); setPage(1); }} placeholder="Tìm mã, tên hoặc email" placeholderTextColor={theme.textSecondary} style={[s.input, { borderColor: theme.backgroundSelected, color: theme.text }]} /><Pressable onPress={() => { setSearch(input.trim()); setPage(1); }} style={s.primary}><ThemedText type="smallBold" style={s.white}>Tìm</ThemedText></Pressable></ThemedView>{remove.isError ? <ThemedText type="small" style={s.danger}>{error(remove.error)}</ThemedText> : null}</ThemedView>}
    ListEmptyComponent={query.isPending ? <ActivityIndicator color={theme.text} /> : <ThemedText type="small">{query.isError ? error(query.error) : 'Chưa có sinh viên trong lớp.'}</ThemedText>} ListFooterComponent={data ? <ThemedView style={s.pagination}><Pressable disabled={current <= 1} onPress={() => setPage((v) => Math.max(1, v - 1))}><ThemedText type="smallBold">Trước</ThemedText></Pressable><ThemedText type="small">Trang {current}/{total || 1}</ThemedText><Pressable disabled={!total || current >= total} onPress={() => setPage((v) => v + 1)}><ThemedText type="smallBold">Sau</ThemedText></Pressable></ThemedView> : null} contentContainerStyle={s.content} refreshing={query.isRefetching} onRefresh={() => void query.refetch()} /></ThemedView>;
}
const s = StyleSheet.create({ container: { flex: 1 }, content: { gap: Spacing.two, padding: Spacing.four }, header: { gap: Spacing.two, paddingBottom: Spacing.three }, row: { flexDirection: 'row', gap: Spacing.two }, input: { borderWidth: 1, borderRadius: Spacing.two, flex: 1, padding: Spacing.two }, primary: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: '#0A7EA4', borderRadius: Spacing.two, justifyContent: 'center', padding: Spacing.two }, white: { color: '#FFF' }, card: { gap: Spacing.one, padding: Spacing.three, borderRadius: Spacing.two }, danger: { color: '#B42318' }, pagination: { flexDirection: 'row', justifyContent: 'space-between', paddingTop: Spacing.three } });
