import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, TextInput } from 'react-native';

import { ApiClientError } from '@/api/api-client';
import { commitClassCopies, previewClassCopies, type ClassCopyDraft, type ClassCopyValues, validateClassCopies } from '@/api/classes';
import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { Spacing } from '@/constants/theme';
import { useTheme } from '@/hooks/use-theme';

function errorMessage(error: unknown, fallback: string) { return error instanceof ApiClientError ? `${error.code ? `${error.code}: ` : ''}${error.message}` : fallback; }
function fingerprint(drafts: ClassCopyDraft[]) { return JSON.stringify(drafts); }

export default function ClassCopyPreviewScreen() {
  const { ids = '' } = useLocalSearchParams<{ ids?: string }>(); const router = useRouter(); const client = useQueryClient(); const theme = useTheme();
  const selectedIds = useMemo(() => ids.split(',').filter(Boolean), [ids]); const preview = useQuery({ queryKey: ['class-copy-preview', selectedIds], queryFn: () => previewClassCopies(selectedIds), enabled: Boolean(selectedIds.length) });
  const [overrides, setOverrides] = useState<ClassCopyDraft[] | null>(null); const [validation, setValidation] = useState<Record<string, { status: 'valid' | 'invalid'; errors: Record<string, string> }>>({}); const [validatedFingerprint, setValidatedFingerprint] = useState<string | null>(null); const [editing, setEditing] = useState<string | null>(null);
  const drafts = overrides ?? preview.data?.data.drafts ?? []; const currentFingerprint = fingerprint(drafts);
  const validate = useMutation({ mutationFn: () => validateClassCopies(drafts), onSuccess: (response) => { setValidation(Object.fromEntries(response.data.rows.map((row) => [row.draftKey, row]))); setValidatedFingerprint(currentFingerprint); } });
  const commit = useMutation({ mutationFn: () => commitClassCopies(drafts), onSuccess: async (response) => { await client.invalidateQueries({ queryKey: ['classes'] }); Alert.alert('Sao chép thành công', `Đã tạo ${response.data.created.length} lớp.`); router.replace('/classes'); } });
  const validCurrent = validatedFingerprint === currentFingerprint && drafts.length > 0 && Object.values(validation).every((row) => row.status === 'valid');
  const update = (key: string, values: ClassCopyValues) => { setOverrides((current) => (current ?? drafts).map((draft) => draft.draftKey === key ? { ...draft, values } : draft)); setValidatedFingerprint(null); };
  if (preview.isPending) return <Centered><ActivityIndicator size="large" /></Centered>;
  if (preview.isError) return <Centered><ThemedText type="smallBold">Không thể tạo bản nháp</ThemedText><ThemedText type="small">{errorMessage(preview.error, 'Vui lòng thử lại.')}</ThemedText></Centered>;
  return <ThemedView style={s.container}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><ThemedView type="backgroundElement" style={s.card}><ThemedText type="subtitle">Xem trước sao chép lớp</ThemedText><ThemedText type="small">Nguồn: {selectedIds.length} · Bản nháp: {drafts.length}</ThemedText>{preview.data?.data.notFoundIds.length ? <ThemedText type="small" style={s.error}>Không tìm thấy: {preview.data.data.notFoundIds.join(', ')}</ThemedText> : null}{validatedFingerprint !== null && validatedFingerprint !== currentFingerprint ? <ThemedText type="small" style={s.error}>Bản nháp đã thay đổi; hãy kiểm tra lại.</ThemedText> : null}</ThemedView>{drafts.map((draft) => <ThemedView key={draft.draftKey} type="backgroundElement" style={s.card}><ThemedText type="smallBold">{draft.values.code} · {draft.values.name}</ThemedText><ThemedText type="small" themeColor="textSecondary">Nguồn #{draft.sourceId}</ThemedText>{draft.values.description ? <ThemedText type="small">{draft.values.description}</ThemedText> : null}{Object.entries(validation[draft.draftKey]?.errors ?? {}).map(([field, value]) => <ThemedText key={field} type="small" style={s.error}>{field}: {value}</ThemedText>)}<Pressable onPress={() => setEditing(draft.draftKey)} style={s.secondary}><ThemedText type="smallBold">Sửa bản nháp</ThemedText></Pressable></ThemedView>)}{validate.isError ? <ThemedText type="small" style={s.error}>{errorMessage(validate.error, 'Không thể kiểm tra.')}</ThemedText> : null}{commit.isError ? <ThemedText type="small" style={s.error}>{errorMessage(commit.error, 'Không thể lưu.')}</ThemedText> : null}<Pressable disabled={!drafts.length || validate.isPending} onPress={() => validate.mutate()} style={[s.secondary, (!drafts.length || validate.isPending) && s.disabled]}><ThemedText type="smallBold">{validate.isPending ? 'Đang kiểm tra...' : 'Kiểm tra bản nháp'}</ThemedText></Pressable><Pressable disabled={!validCurrent || commit.isPending} onPress={() => Alert.alert('Lưu bản sao?', `Tạo ${drafts.length} lớp mới.`, [{ text: 'Hủy', style: 'cancel' }, { text: 'Lưu', onPress: () => commit.mutate() }])} style={[s.primary, (!validCurrent || commit.isPending) && s.disabled]}><ThemedText type="smallBold" style={s.white}>{commit.isPending ? 'Đang lưu...' : 'Lưu bản sao'}</ThemedText></Pressable></ScrollView>{editing ? <Editor draft={drafts.find((draft) => draft.draftKey === editing)!} color={theme.text} onClose={() => setEditing(null)} onSave={(values) => { update(editing, values); setEditing(null); }} /> : null}</ThemedView>;
}

function Editor({ draft, color, onClose, onSave }: { draft: ClassCopyDraft; color: string; onClose: () => void; onSave: (values: ClassCopyValues) => void }) { const [values, setValues] = useState(draft.values); return <ThemedView style={s.editor}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><ThemedText type="subtitle">Sửa bản nháp</ThemedText><TextInput value={values.code} onChangeText={(code) => setValues((value) => ({ ...value, code }))} placeholder="Mã lớp" style={[s.input, { color }]} /><TextInput value={values.name} onChangeText={(name) => setValues((value) => ({ ...value, name }))} placeholder="Tên lớp" style={[s.input, { color }]} /><TextInput value={values.description} onChangeText={(description) => setValues((value) => ({ ...value, description }))} placeholder="Mô tả" multiline style={[s.input, s.multiline, { color }]} /><Pressable onPress={() => onSave(values)} style={s.primary}><ThemedText type="smallBold" style={s.white}>Áp dụng</ThemedText></Pressable><Pressable onPress={onClose} style={s.secondary}><ThemedText type="smallBold">Hủy</ThemedText></Pressable></ScrollView></ThemedView>; }
function Centered({ children }: { children: React.ReactNode }) { return <ThemedView style={s.centered}>{children}</ThemedView>; }
const s = StyleSheet.create({ container: { flex: 1 }, content: { gap: Spacing.three, padding: Spacing.four }, card: { gap: Spacing.two, padding: Spacing.three, borderRadius: Spacing.two }, primary: { alignItems: 'center', backgroundColor: '#0A7EA4', borderRadius: Spacing.two, padding: Spacing.three }, secondary: { alignSelf: 'flex-start', borderColor: '#0A7EA4', borderRadius: Spacing.two, borderWidth: 1, paddingHorizontal: Spacing.three, paddingVertical: Spacing.two }, white: { color: '#FFFFFF' }, disabled: { opacity: .45 }, error: { color: '#B42318' }, editor: { ...StyleSheet.absoluteFill, zIndex: 2 }, input: { borderColor: '#0A7EA4', borderRadius: Spacing.two, borderWidth: 1, fontSize: 16, minHeight: 44, padding: Spacing.two }, multiline: { minHeight: 96, textAlignVertical: 'top' }, centered: { alignItems: 'center', flex: 1, gap: Spacing.two, justifyContent: 'center', padding: Spacing.four } });
